package com.mdo.domainobject;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.mdo.domainobject.Oil;
import com.mdo.domainobject.OilApplication;
import com.mdo.domainobject.OilApplicationDao;
import com.mdo.domainobject.OilDao;
import com.mdo.domainobject.Symptom;
import com.mdo.domainobject.SymptomApplication;
import com.mdo.domainobject.SymptomApplicationDao;
import com.mdo.domainobject.SymptomDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig oilDaoConfig;
    private final DaoConfig symptomDaoConfig;
    private final DaoConfig oilApplicationDaoConfig;
    private final DaoConfig symptomApplicationDaoConfig;

    private final OilDao oilDao;
    private final SymptomDao symptomDao;
    private final OilApplicationDao oilApplicationDao;
    private final SymptomApplicationDao symptomApplicationDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        oilDaoConfig = daoConfigMap.get(OilDao.class).clone();
        oilDaoConfig.initIdentityScope(type);

        symptomDaoConfig = daoConfigMap.get(SymptomDao.class).clone();
        symptomDaoConfig.initIdentityScope(type);

        oilApplicationDaoConfig = daoConfigMap.get(OilApplicationDao.class).clone();
        oilApplicationDaoConfig.initIdentityScope(type);

        symptomApplicationDaoConfig = daoConfigMap.get(SymptomApplicationDao.class).clone();
        symptomApplicationDaoConfig.initIdentityScope(type);

        oilDao = new OilDao(oilDaoConfig, this);
        symptomDao = new SymptomDao(symptomDaoConfig, this);
        oilApplicationDao = new OilApplicationDao(oilApplicationDaoConfig, this);
        symptomApplicationDao = new SymptomApplicationDao(symptomApplicationDaoConfig, this);

        registerDao(Oil.class, oilDao);
        registerDao(Symptom.class, symptomDao);
        registerDao(OilApplication.class, oilApplicationDao);
        registerDao(SymptomApplication.class, symptomApplicationDao);
    }
    
    public void clear() {
        oilDaoConfig.getIdentityScope().clear();
        symptomDaoConfig.getIdentityScope().clear();
        oilApplicationDaoConfig.getIdentityScope().clear();
        symptomApplicationDaoConfig.getIdentityScope().clear();
    }

    public OilDao getOilDao() {
        return oilDao;
    }

    public SymptomDao getSymptomDao() {
        return symptomDao;
    }

    public OilApplicationDao getOilApplicationDao() {
        return oilApplicationDao;
    }

    public SymptomApplicationDao getSymptomApplicationDao() {
        return symptomApplicationDao;
    }

}
