package com.mdo.domainobject;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table OIL.
 */
public class Oil implements Serializable{

    private Long id;
    private String name;
    private String scientificName;
    private String database;
    private String description;
    private String uses;
    private String classification;
    private String systemsAffected;
    private String aromaticAffects;
    private String safetyPrecautions;
    private String application;
    private String additionalSymbol;
    private String imageURL;
    private Byte isFree;
    private String timestamp;
    private Boolean isSaved;

    public Oil() {
    }

    public Oil(Long id) {
        this.id = id;
    }

    public Oil(Long id, String name, String scientificName, String database, String description, String uses, String classification, String systemsAffected, String aromaticAffects, String safetyPrecautions, String application, String additionalSymbol, String imageURL, Byte isFree, String timestamp, Boolean isSaved) {
        this.id = id;
        this.name = name;
        this.scientificName = scientificName;
        this.database = database;
        this.description = description;
        this.uses = uses;
        this.classification = classification;
        this.systemsAffected = systemsAffected;
        this.aromaticAffects = aromaticAffects;
        this.safetyPrecautions = safetyPrecautions;
        this.application = application;
        this.additionalSymbol = additionalSymbol;
        this.imageURL = imageURL;
        this.isFree = isFree;
        this.timestamp = timestamp;
        this.isSaved = isSaved;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getScientificName() {
        return scientificName;
    }

    public void setScientificName(String scientificName) {
        this.scientificName = scientificName;
    }

    public String getDatabase() {
        return database;
    }

    public void setDatabase(String database) {
        this.database = database;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getUses() {
        return uses;
    }

    public void setUses(String uses) {
        this.uses = uses;
    }

    public String getClassification() {
        return classification;
    }

    public void setClassification(String classification) {
        this.classification = classification;
    }

    public String getSystemsAffected() {
        return systemsAffected;
    }

    public void setSystemsAffected(String systemsAffected) {
        this.systemsAffected = systemsAffected;
    }

    public String getAromaticAffects() {
        return aromaticAffects;
    }

    public void setAromaticAffects(String aromaticAffects) {
        this.aromaticAffects = aromaticAffects;
    }

    public String getSafetyPrecautions() {
        return safetyPrecautions;
    }

    public void setSafetyPrecautions(String safetyPrecautions) {
        this.safetyPrecautions = safetyPrecautions;
    }

    public String getApplication() {
        return application;
    }

    public void setApplication(String application) {
        this.application = application;
    }

    public String getAdditionalSymbol() {
        return additionalSymbol;
    }

    public void setAdditionalSymbol(String additionalSymbol) {
        this.additionalSymbol = additionalSymbol;
    }

    public String getImageURL() {
        return imageURL;
    }

    public void setImageURL(String imageURL) {
        this.imageURL = imageURL;
    }

    public Byte getIsFree() {
        return isFree;
    }

    public void setIsFree(Byte isFree) {
        this.isFree = isFree;
    }

    public String getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(String timestamp) {
        this.timestamp = timestamp;
    }

    public Boolean getIsSaved() {
        return isSaved;
    }

    public void setIsSaved(Boolean isSaved) {
        this.isSaved = isSaved;
    }

}
