package com.mdo.domainobject;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table OIL_APPLICATION.
 */
public class OilApplication {

    private Long id;
    private Integer OilId;
    private String SymbolCode;
    private String Description;
    private Integer ApplicationType;
    private String AdditionalSymbols;

    public OilApplication() {
    }

    public OilApplication(Long id) {
        this.id = id;
    }

    public OilApplication(Long id, Integer OilId, String SymbolCode, String Description, Integer ApplicationType, String AdditionalSymbols) {
        this.id = id;
        this.OilId = OilId;
        this.SymbolCode = SymbolCode;
        this.Description = Description;
        this.ApplicationType = ApplicationType;
        this.AdditionalSymbols = AdditionalSymbols;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getOilId() {
        return OilId;
    }

    public void setOilId(Integer OilId) {
        this.OilId = OilId;
    }

    public String getSymbolCode() {
        return SymbolCode;
    }

    public void setSymbolCode(String SymbolCode) {
        this.SymbolCode = SymbolCode;
    }

    public String getDescription() {
        return Description;
    }

    public void setDescription(String Description) {
        this.Description = Description;
    }

    public Integer getApplicationType() {
        return ApplicationType;
    }

    public void setApplicationType(Integer ApplicationType) {
        this.ApplicationType = ApplicationType;
    }

    public String getAdditionalSymbols() {
        return AdditionalSymbols;
    }

    public void setAdditionalSymbols(String AdditionalSymbols) {
        this.AdditionalSymbols = AdditionalSymbols;
    }

}
