package com.mdo.domainobject;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SYMPTOM_APPLICATION.
 */
public class SymptomApplication {

    private Long id;
    private Integer SymId;
    private String SymbolCode;
    private String Description;
    private Integer ApplicationType;
    private String AdditionalSymbols;

    public SymptomApplication() {
    }

    public SymptomApplication(Long id) {
        this.id = id;
    }

    public SymptomApplication(Long id, Integer SymId, String SymbolCode, String Description, Integer ApplicationType, String AdditionalSymbols) {
        this.id = id;
        this.SymId = SymId;
        this.SymbolCode = SymbolCode;
        this.Description = Description;
        this.ApplicationType = ApplicationType;
        this.AdditionalSymbols = AdditionalSymbols;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getSymId() {
        return SymId;
    }

    public void setSymId(Integer SymId) {
        this.SymId = SymId;
    }

    public String getSymbolCode() {
        return SymbolCode;
    }

    public void setSymbolCode(String SymbolCode) {
        this.SymbolCode = SymbolCode;
    }

    public String getDescription() {
        return Description;
    }

    public void setDescription(String Description) {
        this.Description = Description;
    }

    public Integer getApplicationType() {
        return ApplicationType;
    }

    public void setApplicationType(Integer ApplicationType) {
        this.ApplicationType = ApplicationType;
    }

    public String getAdditionalSymbols() {
        return AdditionalSymbols;
    }

    public void setAdditionalSymbols(String AdditionalSymbols) {
        this.AdditionalSymbols = AdditionalSymbols;
    }

}
