package com.mdo.domainobject;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SYMPTOM.
 */
public class Symptom implements Serializable{

    private Long id;
    private String name;
    private String database;
    private String description;
    private String Blends;
    private String AdditionalProducts;
    private String AdditionalSymbols;
    private String contraindications;
    private String primaryOils;
    private String secondaryOils;
    private String TertiaryOils;
    private Byte isFree;
    private String timestamp;

    public Symptom() {
    }

    public Symptom(Long id) {
        this.id = id;
    }

    public Symptom(Long id, String name, String database, String description, String Blends, String AdditionalProducts, String AdditionalSymbols, String contraindications, String primaryOils, String secondaryOils, String TertiaryOils, Byte isFree, String timestamp) {
        this.id = id;
        this.name = name;
        this.database = database;
        this.description = description;
        this.Blends = Blends;
        this.AdditionalProducts = AdditionalProducts;
        this.AdditionalSymbols = AdditionalSymbols;
        this.contraindications = contraindications;
        this.primaryOils = primaryOils;
        this.secondaryOils = secondaryOils;
        this.TertiaryOils = TertiaryOils;
        this.isFree = isFree;
        this.timestamp = timestamp;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDatabase() {
        return database;
    }

    public void setDatabase(String database) {
        this.database = database;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getBlends() {
        return Blends;
    }

    public void setBlends(String Blends) {
        this.Blends = Blends;
    }

    public String getAdditionalProducts() {
        return AdditionalProducts;
    }

    public void setAdditionalProducts(String AdditionalProducts) {
        this.AdditionalProducts = AdditionalProducts;
    }

    public String getAdditionalSymbols() {
        return AdditionalSymbols;
    }

    public void setAdditionalSymbols(String AdditionalSymbols) {
        this.AdditionalSymbols = AdditionalSymbols;
    }

    public String getContraindications() {
        return contraindications;
    }

    public void setContraindications(String contraindications) {
        this.contraindications = contraindications;
    }

    public String getPrimaryOils() {
        return primaryOils;
    }

    public void setPrimaryOils(String primaryOils) {
        this.primaryOils = primaryOils;
    }

    public String getSecondaryOils() {
        return secondaryOils;
    }

    public void setSecondaryOils(String secondaryOils) {
        this.secondaryOils = secondaryOils;
    }

    public String getTertiaryOils() {
        return TertiaryOils;
    }

    public void setTertiaryOils(String TertiaryOils) {
        this.TertiaryOils = TertiaryOils;
    }

    public Byte getIsFree() {
        return isFree;
    }

    public void setIsFree(Byte isFree) {
        this.isFree = isFree;
    }

    public String getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(String timestamp) {
        this.timestamp = timestamp;
    }

}
